adicionando wireframe de editar perfil
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t15-e1-proj-web-t15-time4-projlivroapp pull request #28
Opened 2023-04-18 15:15 UTC by beltrao-vs

pessoal, revisem por favor essa screen nova e me deem feedbacks!

2023-04-18 15:43 UTC, mfsuzigan requested changes

2023-04-18 15:43 UTC, mfsuzigan commented on docs/wireframes/editar perfil.screen
> +  <widgets xsi:type="model:Text" id="56" x="496" y="591" text="Idade:" measuredWidth="42" measuredHeight="20">
Cara, acho que não faz sentido um campo aberto de Idade. Tipo: qual sistema permite vc editar sua idade manualmente?

Eu iria no sentido de não exibir nada nesse sentido, nem mesmo data de nascimento. Duolingo é assim.

Chuto que as pessoas não gostam de serem lembradas da propria idade :sweat_smile: 
/

2023-04-18 15:43 UTC, mfsuzigan commented on docs/wireframes/editar perfil.screen
> +<?xml version="1.0" encoding="UTF-8"?>
Senti falta de um botão de Salvar ou um comentário à direita na tela dizendo que o salvamento será automático.

Pessoalmente, prefiro o botão

2023-04-18 15:43 UTC, mfsuzigan commented on docs/wireframes/editar perfil.screen
> +  <widgets xsi:type="model:Text" id="60" x="497" y="759" text="Informações pessoais" measuredWidth="190" measuredHeight="25">
Esse subtitulo de "Informações pessoais" logo abaixo do título grande "Informações do perfil"  parece redundante pra mim... sugestão: ou retirá-lo ou colocar o texto como "Bio" pra denotar que é um textinho curto pessoal.

2023-04-18 15:43 UTC, mfsuzigan commented on docs/wireframes/editar perfil.screen
> +<?xml version="1.0" encoding="UTF-8"?>
Será que vc consegue diminuir a área de edição do wireframe pra se conformar somente à janela do browser, do jeito que já fizemos nas outras telas? Olha a diferença:
![image](https://user-images.githubusercontent.com/34263103/232828675-348d2658-5fbc-4a5e-990f-e79518cc63ce.png)
![image](https://user-images.githubusercontent.com/34263103/232828783-17f18fc1-b517-4491-95cc-ae6fefc4d1eb.png)

2023-04-18 18:50 UTC, beltrao-vs commented on docs/wireframes/editar perfil.screen
> +<?xml version="1.0" encoding="UTF-8"?>
![image](https://user-images.githubusercontent.com/128924025/232875039-e47da74c-e7b0-4426-b8b9-85158eb65f29.png)

atualizado

2023-04-18 19:49 UTC, beltrao-vs commented
alterações feitas, quando puderem, revisem por favor!

2023-04-19 14:06 UTC, mfsuzigan approved these changes

2023-04-19 21:25 UTC, acrozinholi approved these changes

2023-04-20 16:43 UTC, merged